import { type NextPage } from "next";
import Head from "next/head";

import type { FormEvent } from "react";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { mutate } = trpc.cv.initCV.useMutation();

  const [testData, setTestData] = useState<string | null>(null);
  const [about, setAbout] = useState<string>("");

  const handleGenerateCv = () => {
    const data = mutate(
      { text: about },
      {
        onSuccess: (res) => {
          console.log("res:", res);
          console.log("parsed:", JSON.parse(res));
          // const test = res.replaceAll("\n", "");
          // const testparse = JSON.parse(JSON.stringify(res));
          // console.log(testparse);
          // console.log(test);
        },
      }
    );
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>CV-Creator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/bulb-ico.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Creator <span className="text-[hsl(280,100%,70%)]">Your</span> CV
          </h1>
          {/* <h3>What are you want to continue?</h3>
          <div className="flex">
            <div className="flex flex-col "> */}
          <textarea
            value={about}
            className="hide-scrollbar h-28 w-80 resize-none rounded-lg bg-black/30 px-3 py-2 text-white/95"
            onChange={(e) => setAbout(e.currentTarget.value)}
          />
          <button
            type="button"
            className="mx-auto my-2 w-40 rounded-md bg-blue-600  transition hover:bg-blue-500 hover:text-white"
            onClick={() => handleGenerateCv()}
          >
            Submit
          </button>
          {/* </div>
            <div>
              <button>Create clear CV</button>
            </div> 
          </div> */}
        </div>
      </main>
    </>
  );
};

export default Home;
